### ISSUE TITLE
LCD Start Sequence

### ISSUE THREAD

**Issue by venturem** [tjaworski/AceMagic-S1-LED-TFT-Linux#11]
Hi,

Since I saw that you had opened up the S1 miniPC, I thought to ask this question.
When you restart the PC, at times do  you get a logo, or "Mini PC" or time on the display ?
Do you have any means to trace the  USB signature sent at that point of time ?

I'm asking because  I suspect there is a subroutine that can redraw the screen by itself (subroutine - which shows the time).
We just need to get hold of the signature and memory space where this routine is located, to play with it.

Thanks.

**Comment by tjaworski** [comment]
The LCD is controlled by the firmware on the HT32 controller board (behind the LCD). When you turn the device on, power is applied to it, and the HT32 goes through its own boot routine, displaying the OEM logo.

<img width="156" alt="boot-screen" src="https://github.com/tjaworski/AceMagic-S1-LED-TFT-Linux/assets/6331880/520c905c-397b-4e26-bfe1-ed99f1d643f0">

Once your OS boots up and the s1panel connects to it, the s1panel or their CYX tool will control the screen via the USB. When you power off your device, it likely receives some kind of USB interface power signal instructing the LCD firmware to display the clock.

I don't have an oscilloscope to confirm this, and to truly understand the firmware, we would need to dump it and disassemble it.

By the way, you can simply pop off the magnetic cover, and the two connections on the edge are for the LCD and LED.

<img width="198" alt="connectors" src="https://github.com/tjaworski/AceMagic-S1-LED-TFT-Linux/assets/6331880/bfc88671-9abb-4ef7-8af5-62232b51294d">

They probably put them there to give the user the ability to unplug them easily. The whole front panel with the LCD and LED actually just pops off. It's held by a couple of plastic leg clips. If you unscrew the plastic frame under the magnetic panel, you will see the plastic clips on that edge. 

On a side note, you can actually order the whole gizmo (controller board and LCD) from Holtek as a development kit. Their SDK actually has sample firmware code. It is not beyond the realm of possibility that someone could write their own custom firmware and flash it. I'm not sure if they have the board in read-only or not, but that could be easily figured out with the HT32 schematics and an oscilloscope.
