### ISSUE TITLE
I want to be able to use it on only terminal

### ISSUE THREAD

**Issue by Kauman189** [tjaworski/AceMagic-S1-LED-TFT-Linux#23]
Im not very good at programming but im trying to use it on a home server i want to be able to monitor and change lcd it is possible whit this repro?

**Comment by tjaworski** [comment]
is your home server a S1 Mini-PC from AceMagic?

**Comment by Kauman189** [comment]
Yes it is, i got the sensors and everything working but i cant get the lcd control

**Comment by tjaworski** [comment]
can you run `lsusb -t -v` and paste the output here.

**Comment by Kauman189** [comment]
Im srry for this late response, i fix it, was a firewall issue whit other services, thanks anyways for the feedback was fast, thanks for the amazing work
