### ISSUE TITLE
Possibile working with Turing-smart-screen-python?

### ISSUE THREAD

**Issue by qk-li** [tjaworski/AceMagic-S1-LED-TFT-Linux#3]
Any plan to make it work with this project?
https://github.com/mathoudebine/turing-smart-screen-python
I am a C# programmer, new to the embedded/linux world and willing to contribute.

**Comment by tjaworski** [comment]
I am not a python dev, so no. soon I will be releasing a node.js version of the panel software that will have a web front-end to configure it, rest api, and eventually a Batocera.linux plugin.  Maybe you can ask the guys over at [turing-smart-screen-python](https://github.com/mathoudebine/turing-smart-screen-python/issues) if they are willing to add support for this. 

I am still looking for info on the fan speed if anyone knows...
