### ISSUE TITLE
gosh i want this code so bad

### ISSUE THREAD

**Issue by alycecil** [tjaworski/AceMagic-S1-LED-TFT-Linux#4]
I want to play with this and tweak it so very much~

**Comment by tjaworski** [comment]
yep, coming soon to a repo near you. working on the front end now. :)

here is a little preview:

<img width="1108" alt="Screenshot 2024-03-30 at 3 38 19 PM" src="https://github.com/tjaworski/AceMagic-S1-LED-TFT-Linux/assets/6331880/21101e21-e0f3-4482-b4a9-6a3fdf398043">

**Comment by yeorinhieut** [comment]
Waiting for it! 🥰

**Comment by tjaworski** [comment]
I posted the code for the s1panel, closing this issue.
