### ISSUE TITLE
WEB GUI not accessible after installation

### ISSUE THREAD

**Issue by mikolka-lsh** [tjaworski/AceMagic-S1-LED-TFT-Linux#8]
Hi.

How could I troubleshoot this bocause after:

- installing nodjs:
$ node -v
v18.19.0

- installing lm-sensors:
$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +47.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +43.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +43.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:        +43.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:        +43.0°C  (high = +105.0°C, crit = +105.0°C)

- installing AceMagic-S1-LED-TFT-Linux:
$ sudo ./install 
Home Directory is /home/mikolka/CustomApp/acemagic/s1panel
./install: line 25: npm: command not found
./install: line 26: npm: command not found
Building GUI
./install: line 28: npm: command not found
Install Service...
Reload Service Daemon...
Enable s1panel...
Created symlink /etc/systemd/system/multi-user.target.wants/s1panel.service → /etc/systemd/system/s1panel.service.
Start s1panel...
Done!
● s1panel.service - "S1 Panel"
     Loaded: loaded (/etc/systemd/system/s1panel.service; enabled; preset: enabled)
     Active: active (running) since Mon 2024-04-08 14:24:41 EEST; 38ms ago
   Main PID: 3234654 (node)
      Tasks: 1 (limit: 18869)
     Memory: 492.0K
     CGroup: /system.slice/s1panel.service
             └─3234654 /usr/bin/node main.js

Apr 08 14:24:41 smart systemd[1]: Started s1panel.service - "S1 Panel".

I can't access http://192.168.76.10:8686/ where my server IP - 192.168.76.10.... :(

when I'm trying to check port 8686 - it's "empty":
$ sudo lsof -i:8686  - return nothing...

How could I troubleshoot this?

**Comment by tjaworski** [comment]
I forgot you also need npm

```
sudo apt install nodejs
sudo apt install npm
$ node -v
v18.13.0
$ npm -v
9.2.0
```
updated the readme.

**Comment by mikolka-lsh** [comment]
Thanks!
Now it works but listening only on loopback and as far as I don't have a gui on my server - I can't use web-based interface :(

node       661            root   27u  IPv4  13999      0t0  TCP 127.0.0.1:8686 (LISTEN)

How can I make it listen on all interfaces on a given port?

**Comment by tjaworski** [comment]
stop the service, edit the config.json, and change the listen to 0.0.0.0:8686 and you will be able to access it remotely. 
```
sudo service s1panel stop
vi config.json
sudo service s1panel start
```

**Comment by mikolka-lsh** [comment]
Thanks!

Now all works as a charm! :)
And more - now I even understand that I could configure it throw config files :+1: 
So now I'm going to find and change cpu_temp from Farengeith to Celcium while we don't have such switch in GUI... :)
