### ISSUE TITLE
Panel cycles through "screens" after some time

### ISSUE THREAD

**Issue by mreymann** [tjaworski/AceMagic-S1-LED-TFT-Linux#9]
This is getting better all the time! Thanks for your effort!
I've updated s1panel today.

My favourite screen is "Screen 2 Charts".

After some time, the display changes to the two other screens. Is this intended?

 One minor thing: I've set "fahrenheit": false in config.json. Is there also a setting in the WebGUI?

**Comment by tjaworski** [comment]
1. the demo theme will cycle between the different screens, each screen has a duration time to stay on it. change the duration for it to stay on that screen.  (the panel with the screen name, will have a duration: 60000ms)
2. yes, the sensor's config will be added to the web gui in future updates. (it is on my really long list of things to-do)

feedback is greatly appreciated!
